#pragma once
#include "messages.hpp"
#include <boost/describe.hpp>


// auto generated by eobi_gen(WIP) from : https://www.eurex.com/resource/blob/4332346/4b66e684ab3cf9e2cee92ca534cd1a68/data/T7_R.13.1_%20EOBI_XML_Representation_Version_2.zip#eobi.xml

namespace eobi::v13_1 {

BOOST_DESCRIBE_STRUCT(MessageHeaderComp, (), (
		bodyLen,
		templateID,
		msgSeqNum
))

BOOST_DESCRIBE_ENUM(ProductComplex,SimpleInstrument,StandardOptionStrategy,NonStandardOptionStrategy,VolatilityStrategy,FuturesSpread,InterProductSpread,StandardFuturesStrategy,PackAndBundle,Strip,FlexibleInstrument,CommodityStrip,ScaledSimpleInstrument,NonStandardVolatilityStrategy,TotalReturnFutureStrategy,NoValue)
BOOST_DESCRIBE_ENUM(ImpliedMarketIndicator,NotImplied,ImpliedInOut,NoValue)
BOOST_DESCRIBE_ENUM(LastFragment,N,Y,NoValue)
BOOST_DESCRIBE_ENUM(LegSecurityType,LegSecurityMultiLeg,LegSecurityUnderlyingLeg,NoValue)
BOOST_DESCRIBE_ENUM(LegSide,Buy,Sell,NoValue)
BOOST_DESCRIBE_ENUM(RelatedPriceType,Basis,NoValue)
BOOST_DESCRIBE_ENUM(TradingStyle,Regular,TRF_TAC,TRF_TAM,MOC,NoValue)
BOOST_DESCRIBE_STRUCT(InstrmtLegGrpComp, (), (
		legSymbol,
		pad4,
		legSecurityID,
		legPrice,
		legRatioQty,
		legSecurityType,
		legSide,
		relatedPriceType,
		tradingStyle,
		relatedPrice
))

BOOST_DESCRIBE_STRUCT(AddComplexInstrument, (), (
		messageHeader,
		securityID,
		transactTime,
		securityDesc,
		securitySubType,
		productComplex,
		impliedMarketIndicator,
		quantityScalingFactor,
		legRatioMultiplier,
		noLegs,
		pad2,
		lastFragment,
		instrmtLegGrp
))

BOOST_DESCRIBE_ENUM(SecurityType,OPT,FUT,MLEG,NoValue)
BOOST_DESCRIBE_ENUM(PutOrCall,Put,Call,NoValue)
BOOST_DESCRIBE_ENUM(ExerciseStyle,European,American,NoValue)
BOOST_DESCRIBE_ENUM(SettlMethod,Cash,Physical,NoValue)
BOOST_DESCRIBE_STRUCT(AddFlexibleInstrument, (), (
		messageHeader,
		securityID,
		transactTime,
		securityDesc,
		securityType,
		putOrCall,
		exerciseStyle,
		settlMethod,
		maturityDate,
		strikePrice,
		optAttribute,
		contractDate,
		securityReferenceDataSupplement,
		pad4
))

BOOST_DESCRIBE_STRUCT(RelatedInstrumentGrpComp, (), (
		relatedSecurityID
))

BOOST_DESCRIBE_STRUCT(AddScaledSimpleInstrument, (), (
		messageHeader,
		securityID,
		transactTime,
		securityDesc,
		securityType,
		pad1,
		quantityScalingFactor,
		pad4,
		relatedInstrumentGrp
))

BOOST_DESCRIBE_ENUM(PotentialSecurityTradingEvent,None,PriceVolatilityAuctionIsExtended,NoValue)
BOOST_DESCRIBE_ENUM(BidOrdType,Market,NoValue)
BOOST_DESCRIBE_ENUM(OfferOrdType,Market,NoValue)
BOOST_DESCRIBE_STRUCT(AuctionBBO, (), (
		messageHeader,
		transactTime,
		securityID,
		bidPx,
		offerPx,
		bidSize,
		offerSize,
		potentialSecurityTradingEvent,
		bidOrdType,
		offerOrdType,
		pad5
))

BOOST_DESCRIBE_ENUM(SecurityTradingStatus,TradingHalt,MarketImbalanceBuy,MarketImbalanceSell,Closed,Restricted,Book,Continuous,OpeningAuction,OpeningAuctionFreeze,IntradayAuction,IntradayAuctionFreeze,CircuitBreakerAuction,CircuitBreakerAuctionFreeze,ClosingAuction,ClosingAuctionFreeze,IPOAuction,IPOAuctionFreeze,PreCall,Call,Freeze,TradeAtClose,CircuitBreakerAuctionTriggeredByStaticLimitBreach,CircuitBreakerAuctionTriggeredByStaticLimitBreachFreeze,NoValue)
BOOST_DESCRIBE_STRUCT(AuctionClearingPrice, (), (
		messageHeader,
		transactTime,
		securityID,
		lastPx,
		lastQty,
		imbalanceQty,
		securityTradingStatus,
		potentialSecurityTradingEvent,
		pad6
))

BOOST_DESCRIBE_ENUM(Side,Buy,Sell,NoValue)
BOOST_DESCRIBE_ENUM(CrossRequestType,CrossAnnouncement,LiquidityImprovementCross,NoValue)
BOOST_DESCRIBE_ENUM(InputSource,CLIPClientBroker,NoValue)
BOOST_DESCRIBE_STRUCT(CrossRequest, (), (
		messageHeader,
		securityID,
		lastPx,
		lastQty,
		side,
		crossRequestType,
		inputSource,
		pad5,
		transactTime
))

BOOST_DESCRIBE_ENUM(AggressorSide,Buy,Sell,NoValue)
BOOST_DESCRIBE_ENUM(TradeCondition,ImpliedTrade,OutOfSequence,MidpointPrice,TradingOnTermsOfIssue,SpecialAuction,TradeAtClose,Retail,NoValue)
BOOST_DESCRIBE_STRUCT(RemainingOrderDetailsComp, (), (
		trdRegTSPrevTimePriority,
		displayQty,
		price
))

BOOST_DESCRIBE_STRUCT(ExecutionSummary, (), (
		messageHeader,
		securityID,
		requestTime,
		execID,
		lastQty,
		aggressorSide,
		pad1,
		tradeCondition,
		tradingHHIIndicator,
		pad3,
		lastPx,
		remainingOrderDetails,
		restingHiddenQty,
		restingCxlQty,
		aggressorTime
))

BOOST_DESCRIBE_ENUM(OrdType,Market,NoValue)
BOOST_DESCRIBE_ENUM(AlgorithmicTradeIndicator,AlgorithmicTrade,NoValue)
BOOST_DESCRIBE_ENUM(HHIIndicator,NoUpdate,NoValue)
BOOST_DESCRIBE_STRUCT(FullOrderExecution, (), (
		messageHeader,
		side,
		ordType,
		algorithmicTradeIndicator,
		hHIIndicator,
		trdMatchID,
		price,
		trdRegTSTimePriority,
		securityID,
		lastQty,
		lastPx
))

BOOST_DESCRIBE_STRUCT(Heartbeat, (), (
		messageHeader,
		lastMsgSeqNumProcessed,
		pad4
))

BOOST_DESCRIBE_ENUM(SecurityStatus,Active,Inactive,Expired,KnockedOut,KnockOutRevoked,Suspended,PendingDeletion,KnockedOutAndSuspended,NoValue)
BOOST_DESCRIBE_ENUM(MarketCondition,Normal,Stressed,NoValue)
BOOST_DESCRIBE_ENUM(FastMarketIndicator,No,Yes,NoValue)
BOOST_DESCRIBE_ENUM(SecurityTradingEvent,PriceVolatilityAuctionIsExtended,PriceVolatilityAuctionIsExtendedAgain,NoValue)
BOOST_DESCRIBE_ENUM(SoldOutIndicator,SoldOut,NoValue)
BOOST_DESCRIBE_ENUM(TESSecurityStatus,Active,Inactive,Expired,Suspended,NoValue)
BOOST_DESCRIBE_STRUCT(InstrumentStateChange, (), (
		messageHeader,
		securityID,
		securityStatus,
		securityTradingStatus,
		marketCondition,
		fastMarketIndicator,
		securityTradingEvent,
		soldOutIndicator,
		pad2,
		highPx,
		lowPx,
		transactTime,
		tESSecurityStatus,
		pad7
))

BOOST_DESCRIBE_ENUM(MDOriginType,Book,OffBook,NoValue)
BOOST_DESCRIBE_ENUM(MDEntryType,Trade,OpeningPrice,ClosingPrice,HighPrice,LowPrice,TradeVolume,PreviousClosingPrice,OpeningAuction,IntradayAuction,CircuitBreakerAuction,ClosingAuction,IPOAuction,NoValue)
BOOST_DESCRIBE_ENUM(TrdType,BlockTrade,EFP,EFS,OTC,ExchangeBasisFacility,VolaTrade,EFPFinTrade,EFPIndexFuturesTrade,BlockTradeAtMarket,XetraEurexEnlightTriggeredTrade,BlockQTPIPTrade,DeltaTradeAtMarket,NoValue)
BOOST_DESCRIBE_ENUM(MultiLegReportingType,SingleSecurity,IndividualLegOfAMultiLegSecurity,MultiLegSecurity,NoValue)
BOOST_DESCRIBE_ENUM(MultiLegPriceModel,Standard,UserDefined,NoValue)
BOOST_DESCRIBE_STRUCT(MDInstrumentEntryGrpComp, (), (
		mDEntryPx,
		mDEntrySize,
		mDOriginType,
		mDEntryType,
		tradeCondition,
		trdType,
		multiLegReportingType,
		multiLegPriceModel,
		nonDisclosedTradeVolume
))

BOOST_DESCRIBE_STRUCT(InstrumentSummary, (), (
		messageHeader,
		securityID,
		lastUpdateTime,
		trdRegTSExecutionTime,
		totNoOrders,
		securityStatus,
		securityTradingStatus,
		marketCondition,
		fastMarketIndicator,
		securityTradingEvent,
		soldOutIndicator,
		highPx,
		lowPx,
		productComplex,
		noMDEntries,
		tESSecurityStatus,
		pad5,
		mDInstrumentEntryGrp
))

BOOST_DESCRIBE_STRUCT(MDTradeEntryGrpComp, (), (
		mDEntryPx,
		mDEntrySize,
		mDEntryType,
		pad7
))

BOOST_DESCRIBE_ENUM(InstrumentScopeProductComplex,SimpleInstrument,StandardOptionStrategy,NonStandardOptionStrategy,VolatilityStrategy,FuturesSpread,InterProductSpread,StandardFuturesStrategy,PackAndBundle,Strip,FlexibleInstrument,CommodityStrip,ScaledSimpleInstrument,NonStandardVolatilityStrategy,TotalReturnFutureStrategy,NoValue)
BOOST_DESCRIBE_ENUM(SecurityMassStatus,Active,Inactive,Expired,KnockedOut,KnockOutRevoked,Suspended,PendingDeletion,KnockedOutAndSuspended,NoValue)
BOOST_DESCRIBE_ENUM(SecurityMassTradingStatus,TradingHalt,MarketImbalanceBuy,MarketImbalanceSell,Closed,Restricted,Book,Continuous,OpeningAuction,OpeningAuctionFreeze,IntradayAuction,IntradayAuctionFreeze,CircuitBreakerAuction,CircuitBreakerAuctionFreeze,ClosingAuction,ClosingAuctionFreeze,IPOAuction,IPOAuctionFreeze,PreCall,Call,Freeze,TradeAtClose,CircuitBreakerAuctionTriggeredByStaticLimitBreach,CircuitBreakerAuctionTriggeredByStaticLimitBreachFreeze,NoValue)
BOOST_DESCRIBE_ENUM(MassMarketCondition,Normal,Stressed,NoValue)
BOOST_DESCRIBE_ENUM(SecurityMassTradingEvent,PriceVolatilityAuctionIsExtended,PriceVolatilityAuctionIsExtendedAgain,NoValue)
BOOST_DESCRIBE_ENUM(MassSoldOutIndicator,SoldOut,NoValue)
BOOST_DESCRIBE_ENUM(TESSecurityMassStatus,Active,Inactive,Expired,Suspended,NoValue)
BOOST_DESCRIBE_STRUCT(SecMassStatGrpComp, (), (
		securityID,
		highPx,
		lowPx,
		securityStatus,
		securityTradingStatus,
		marketCondition,
		securityTradingEvent,
		soldOutIndicator,
		tESSecurityStatus,
		pad2
))

BOOST_DESCRIBE_STRUCT(MassInstrumentStateChange, (), (
		messageHeader,
		instrumentScopeProductComplex,
		securityMassStatus,
		securityMassTradingStatus,
		massMarketCondition,
		fastMarketIndicator,
		securityMassTradingEvent,
		massSoldOutIndicator,
		tESSecurityMassStatus,
		transactTime,
		lastFragment,
		noRelatedSym,
		pad6,
		secMassStatGrp
))

BOOST_DESCRIBE_STRUCT(OrderDetailsComp, (), (
		trdRegTSTimePriority,
		displayQty,
		side,
		ordType,
		hHIIndicator,
		pad5,
		price
))

BOOST_DESCRIBE_STRUCT(OrderAdd, (), (
		messageHeader,
		requestTime,
		securityID,
		orderDetails
))

BOOST_DESCRIBE_STRUCT(OrderDelete, (), (
		messageHeader,
		requestTime,
		transactTime,
		securityID,
		orderDetails
))

BOOST_DESCRIBE_STRUCT(OrderMassDelete, (), (
		messageHeader,
		securityID,
		transactTime
))

BOOST_DESCRIBE_ENUM(PrevPriceHHIIndicator,NoUpdate,NoValue)
BOOST_DESCRIBE_STRUCT(OrderModify, (), (
		messageHeader,
		requestTime,
		trdRegTSPrevTimePriority,
		prevPrice,
		prevDisplayQty,
		securityID,
		orderDetails,
		prevPriceHHIIndicator,
		pad7
))

BOOST_DESCRIBE_STRUCT(OrderModifySamePrio, (), (
		messageHeader,
		requestTime,
		transactTime,
		prevDisplayQty,
		securityID,
		orderDetails
))

BOOST_DESCRIBE_ENUM(CompletionIndicator,Incomplete,Complete,NoValue)
BOOST_DESCRIBE_ENUM(ApplSeqResetIndicator,NoReset,Reset,NoValue)
BOOST_DESCRIBE_STRUCT(PacketHeader, (), (
		messageHeader,
		applSeqNum,
		marketSegmentID,
		partitionID,
		completionIndicator,
		applSeqResetIndicator,
		dSCP,
		pad4,
		transactTime
))

BOOST_DESCRIBE_STRUCT(PartialOrderExecution, (), (
		messageHeader,
		side,
		ordType,
		algorithmicTradeIndicator,
		hHIIndicator,
		trdMatchID,
		price,
		trdRegTSTimePriority,
		securityID,
		lastQty,
		lastPx
))

BOOST_DESCRIBE_ENUM(TradingSessionID,Day,Morning,Evening,AfterHours,Holiday,NoValue)
BOOST_DESCRIBE_ENUM(TradingSessionSubID,PreTrading,Continuous,Closing,PostTrading,Quiescent,NoValue)
BOOST_DESCRIBE_ENUM(TradSesStatus,Halted,Open,Closed,NoValue)
BOOST_DESCRIBE_ENUM(TESTradSesStatus,Halted,Open,Closed,PreClose,NoValue)
BOOST_DESCRIBE_STRUCT(ProductStateChange, (), (
		messageHeader,
		tradingSessionID,
		tradingSessionSubID,
		tradSesStatus,
		marketCondition,
		fastMarketIndicator,
		tESTradSesStatus,
		pad2,
		transactTime
))

BOOST_DESCRIBE_STRUCT(ProductSummary, (), (
		messageHeader,
		lastMsgSeqNumProcessed,
		tradingSessionID,
		tradingSessionSubID,
		tradSesStatus,
		marketCondition,
		fastMarketIndicator,
		tESTradSesStatus,
		pad6
))

BOOST_DESCRIBE_STRUCT(QuoteRequest, (), (
		messageHeader,
		securityID,
		lastQty,
		side,
		pad7,
		transactTime
))

BOOST_DESCRIBE_STRUCT(SnapshotOrder, (), (
		messageHeader,
		orderDetails
))

BOOST_DESCRIBE_STRUCT(TESTradeReport, (), (
		messageHeader,
		securityID,
		transactTime,
		lastQty,
		lastPx,
		trdMatchID,
		trdType,
		tradeCondition,
		multiLegReportingType,
		multiLegPriceModel,
		pad6,
		nonDisclosedTradeVolume,
		transBkdTime,
		numberOfBuySides,
		numberOfSellSides,
		pad4
))

BOOST_DESCRIBE_STRUCT(TopOfBook, (), (
		messageHeader,
		transactTime,
		securityID,
		bidPx,
		offerPx,
		bidSize,
		offerSize,
		numberOfBuyOrders,
		numberOfSellOrders,
		pad4
))

BOOST_DESCRIBE_ENUM(MatchType,ConfirmedTradeReport,CrossAuction,CallAuction,LiquidityImprovementCross,ContinuousAuction,NoValue)
BOOST_DESCRIBE_ENUM(MatchSubType,OpeningAuction,ClosingAuction,IntradayAuction,CircuitBreakerAuction,IPOAuction,NoValue)
BOOST_DESCRIBE_STRUCT(TradeReport, (), (
		messageHeader,
		securityID,
		transactTime,
		lastQty,
		lastPx,
		trdMatchID,
		matchType,
		matchSubType,
		algorithmicTradeIndicator,
		pad1,
		tradeCondition,
		pad6
))

BOOST_DESCRIBE_STRUCT(TradeReversal, (), (
		messageHeader,
		securityID,
		transactTime,
		lastQty,
		lastPx,
		trdRegTSExecutionTime,
		trdMatchID,
		tradeCondition,
		mDOriginType,
		noMDEntries,
		mDTradeEntryGrp
))



} // namespace eobi::v13_1
