#pragma once
#include "messages.hpp"
#include <boost/describe.hpp>


// auto generated by cme_gen(WIP) from : https://www.cmegroup.com/ftp/SBEFix/Production/Templates/templates_FixBinary.xml

namespace cme::mdp3::v9 {

BOOST_DESCRIBE_STRUCT(Decimal9, (), (
	mantissa,
))

BOOST_DESCRIBE_STRUCT(Decimal9NULL, (), (
	mantissa,
))

BOOST_DESCRIBE_STRUCT(DecimalQty, (), (
	mantissa,
))

BOOST_DESCRIBE_STRUCT(FLOAT, (), (
	mantissa,
))

BOOST_DESCRIBE_STRUCT(MaturityMonthYear, (), (
	year,
	month,
	day,
	week,
))

BOOST_DESCRIBE_STRUCT(PRICE, (), (
	mantissa,
))

BOOST_DESCRIBE_STRUCT(PRICE9, (), (
	mantissa,
))

BOOST_DESCRIBE_STRUCT(PRICENULL, (), (
	mantissa,
))

BOOST_DESCRIBE_STRUCT(PRICENULL9, (), (
	mantissa,
))

BOOST_DESCRIBE_STRUCT(groupSize, (), (
	blockLength,
	numInGroup,
))

BOOST_DESCRIBE_STRUCT(groupSize8Byte, (), (
	blockLength,
	padding_1,
	numInGroup,
))

BOOST_DESCRIBE_STRUCT(groupSizeEncoding, (), (
	blockLength,
	numInGroup,
))

BOOST_DESCRIBE_STRUCT(messageHeader, (), (
	blockLength,
	templateId,
	schemaId,
	version,
))

BOOST_DESCRIBE_ENUM(AggressorSide,NoAggressor,Buy,Sell,)
BOOST_DESCRIBE_ENUM(EventType,Activation,LastEligibleTradeDate,)
BOOST_DESCRIBE_ENUM(HaltReason,GroupSchedule,SurveillanceIntervention,MarketEvent,InstrumentActivation,InstrumentExpiration,Unknown,RecoveryInProcess,)
BOOST_DESCRIBE_ENUM(LegSide,BuySide,SellSide,)
BOOST_DESCRIBE_ENUM(MDEntryType,Bid,Offer,Trade,OpenPrice,SettlementPrice,TradingSessionHighPrice,TradingSessionLowPrice,ClearedVolume,OpenInterest,ImpliedBid,ImpliedOffer,BookReset,SessionHighBid,SessionLowOffer,FixingPrice,ElectronicVolume,ThresholdLimitsandPriceBandVariation,)
BOOST_DESCRIBE_ENUM(MDEntryTypeBook,Bid,Offer,ImpliedBid,ImpliedOffer,BookReset,)
BOOST_DESCRIBE_ENUM(MDEntryTypeDailyStatistics,SettlementPrice,ClearedVolume,OpenInterest,FixingPrice,)
BOOST_DESCRIBE_ENUM(MDEntryTypeStatistics,OpenPrice,HighTrade,LowTrade,HighestBid,LowestOffer,)
BOOST_DESCRIBE_ENUM(MDUpdateAction,New,Change,Delete,DeleteThru,DeleteFrom,Overlay,)
BOOST_DESCRIBE_ENUM(OpenCloseSettlFlag,DailyOpenPrice,IndicativeOpeningPrice,)
BOOST_DESCRIBE_ENUM(OrderUpdateAction,New,Update,Delete,)
BOOST_DESCRIBE_ENUM(PutOrCall,Put,Call,)
BOOST_DESCRIBE_ENUM(SecurityTradingEvent,NoEvent,NoCancel,ResetStatistics,ImpliedMatchingON,ImpliedMatchingOFF,)
BOOST_DESCRIBE_ENUM(SecurityTradingStatus,TradingHalt,Close,NewPriceIndication,ReadyToTrade,NotAvailableForTrading,UnknownorInvalid,PreOpen,PreCross,Cross,PostClose,NoChange,)
BOOST_DESCRIBE_ENUM(SecurityUpdateAction,Add,Delete,Modify,)
BOOST_DESCRIBE_ENUM(InstAttribValue,ElectronicMatchEligible,OrderCrossEligible,BlockTradeEligible,EFPEligible,EBFEligible,EFSEligible,EFREligible,OTCEligible,iLinkIndicativeMassQuotingEligible,NegativeStrikeEligible,NegativePriceOutrightEligible,IsFractional,VolatilityQuotedOption,RFQCrossEligible,ZeroPriceOutrightEligible,DecayingProductEligibility,VariableProductEligibility,DailyProductEligibility,GTOrdersEligibility,ImpliedMatchingEligibility,TriangulationEligible,VariableCabEligible,)
BOOST_DESCRIBE_ENUM(MatchEventIndicator,LastTradeMsg,LastVolumeMsg,LastQuoteMsg,LastStatsMsg,LastImpliedMsg,RecoveryMsg,Reserved,EndOfEvent,)
BOOST_DESCRIBE_ENUM(SettlPriceType,FinalDaily,Actual,Rounded,Intraday,ReservedBits,NullValue,)
BOOST_DESCRIBE_STRUCT(ChannelReset4, (), (
	msg_size,
	message_header,
	transactTime,
	matchEventIndicator,
	noMDEntries,
 ))

BOOST_DESCRIBE_STRUCT(ChannelReset4::NoMDEntries, (), (
	applID,
))

BOOST_DESCRIBE_STRUCT(AdminHeartbeat12, (), (
	msg_size,
	message_header,
))

BOOST_DESCRIBE_STRUCT(AdminLogin15, (), (
	msg_size,
	message_header,
	heartBtInt,
))

BOOST_DESCRIBE_STRUCT(AdminLogout16, (), (
	msg_size,
	message_header,
	text,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionFuture27, (), (
	msg_size,
	message_header,
	matchEventIndicator,
	totNumReports,
	securityUpdateAction,
	lastUpdateTime,
	mDSecurityTradingStatus,
	applID,
	marketSegmentID,
	underlyingProduct,
	securityExchange,
	securityGroup,
	asset,
	symbol,
	securityID,
	securityType,
	cFICode,
	maturityMonthYear,
	currency,
	settlCurrency,
	matchAlgorithm,
	minTradeVol,
	maxTradeVol,
	minPriceIncrement,
	displayFactor,
	mainFraction,
	subFraction,
	priceDisplayFormat,
	unitOfMeasure,
	unitOfMeasureQty,
	tradingReferencePrice,
	settlPriceType,
	openInterestQty,
	clearedVolume,
	highLimitPrice,
	lowLimitPrice,
	maxPriceVariation,
	decayQuantity,
	decayStartDate,
	originalContractSize,
	contractMultiplier,
	contractMultiplierUnit,
	flowScheduleType,
	minPriceIncrementAmount,
	userDefinedInstrument,
	tradingReferenceDate,
	noEvents,
 	noMDFeedTypes,
 	noInstAttrib,
 	noLotTypeRules,
 ))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionFuture27::NoEvents, (), (
	eventType,
	eventTime,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionFuture27::NoMDFeedTypes, (), (
	mDFeedType,
	marketDepth,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionFuture27::NoInstAttrib, (), (
	instAttribValue,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionFuture27::NoLotTypeRules, (), (
	lotType,
	minLotSize,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionSpread29, (), (
	msg_size,
	message_header,
	matchEventIndicator,
	totNumReports,
	securityUpdateAction,
	lastUpdateTime,
	mDSecurityTradingStatus,
	applID,
	marketSegmentID,
	underlyingProduct,
	securityExchange,
	securityGroup,
	asset,
	symbol,
	securityID,
	securityType,
	cFICode,
	maturityMonthYear,
	currency,
	securitySubType,
	userDefinedInstrument,
	matchAlgorithm,
	minTradeVol,
	maxTradeVol,
	minPriceIncrement,
	displayFactor,
	priceDisplayFormat,
	priceRatio,
	tickRule,
	unitOfMeasure,
	tradingReferencePrice,
	settlPriceType,
	openInterestQty,
	clearedVolume,
	highLimitPrice,
	lowLimitPrice,
	maxPriceVariation,
	mainFraction,
	subFraction,
	tradingReferenceDate,
	noEvents,
 	noMDFeedTypes,
 	noInstAttrib,
 	noLotTypeRules,
 	noLegs,
 ))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionSpread29::NoEvents, (), (
	eventType,
	eventTime,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionSpread29::NoMDFeedTypes, (), (
	mDFeedType,
	marketDepth,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionSpread29::NoInstAttrib, (), (
	instAttribValue,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionSpread29::NoLotTypeRules, (), (
	lotType,
	minLotSize,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionSpread29::NoLegs, (), (
	legSecurityID,
	legSide,
	legRatioQty,
	legPrice,
	legOptionDelta,
))

BOOST_DESCRIBE_STRUCT(SecurityStatus30, (), (
	msg_size,
	message_header,
	transactTime,
	securityGroup,
	asset,
	securityID,
	tradeDate,
	matchEventIndicator,
	securityTradingStatus,
	haltReason,
	securityTradingEvent,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshBook32, (), (
	msg_size,
	message_header,
	transactTime,
	matchEventIndicator,
	block_padding,
	noMDEntries,
 	noOrderIDEntries,
 ))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshBook32::NoMDEntries, (), (
	mDEntryPx,
	mDEntrySize,
	securityID,
	rptSeq,
	numberOfOrders,
	mDPriceLevel,
	mDUpdateAction,
	mDEntryType,
	padding,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshBook32::NoOrderIDEntries, (), (
	orderID,
	mDOrderPriority,
	mDDisplayQty,
	referenceID,
	orderUpdateAction,
	padding,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshDailyStatistics33, (), (
	msg_size,
	message_header,
	transactTime,
	matchEventIndicator,
	block_padding,
	noMDEntries,
 ))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshDailyStatistics33::NoMDEntries, (), (
	mDEntryPx,
	mDEntrySize,
	securityID,
	rptSeq,
	tradingReferenceDate,
	settlPriceType,
	mDUpdateAction,
	mDEntryType,
	padding,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshLimitsBanding34, (), (
	msg_size,
	message_header,
	transactTime,
	matchEventIndicator,
	block_padding,
	noMDEntries,
 ))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshLimitsBanding34::NoMDEntries, (), (
	highLimitPrice,
	lowLimitPrice,
	maxPriceVariation,
	securityID,
	rptSeq,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshSessionStatistics35, (), (
	msg_size,
	message_header,
	transactTime,
	matchEventIndicator,
	block_padding,
	noMDEntries,
 ))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshSessionStatistics35::NoMDEntries, (), (
	mDEntryPx,
	securityID,
	rptSeq,
	openCloseSettlFlag,
	mDUpdateAction,
	mDEntryType,
	mDEntrySize,
	padding,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshVolume37, (), (
	msg_size,
	message_header,
	transactTime,
	matchEventIndicator,
	block_padding,
	noMDEntries,
 ))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshVolume37::NoMDEntries, (), (
	mDEntrySize,
	securityID,
	rptSeq,
	mDUpdateAction,
	padding,
))

BOOST_DESCRIBE_STRUCT(SnapshotFullRefresh38, (), (
	msg_size,
	message_header,
	lastMsgSeqNumProcessed,
	totNumReports,
	securityID,
	rptSeq,
	transactTime,
	lastUpdateTime,
	tradeDate,
	mDSecurityTradingStatus,
	highLimitPrice,
	lowLimitPrice,
	maxPriceVariation,
	noMDEntries,
 ))

BOOST_DESCRIBE_STRUCT(SnapshotFullRefresh38::NoMDEntries, (), (
	mDEntryPx,
	mDEntrySize,
	numberOfOrders,
	mDPriceLevel,
	tradingReferenceDate,
	openCloseSettlFlag,
	settlPriceType,
	mDEntryType,
))

BOOST_DESCRIBE_STRUCT(QuoteRequest39, (), (
	msg_size,
	message_header,
	transactTime,
	quoteReqID,
	matchEventIndicator,
	block_padding,
	noRelatedSym,
 ))

BOOST_DESCRIBE_STRUCT(QuoteRequest39::NoRelatedSym, (), (
	symbol,
	securityID,
	orderQty,
	quoteType,
	side,
	padding,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionOption41, (), (
	msg_size,
	message_header,
	matchEventIndicator,
	totNumReports,
	securityUpdateAction,
	lastUpdateTime,
	mDSecurityTradingStatus,
	applID,
	marketSegmentID,
	underlyingProduct,
	securityExchange,
	securityGroup,
	asset,
	symbol,
	securityID,
	securityType,
	cFICode,
	putOrCall,
	maturityMonthYear,
	currency,
	strikePrice,
	strikeCurrency,
	settlCurrency,
	minCabPrice,
	matchAlgorithm,
	minTradeVol,
	maxTradeVol,
	minPriceIncrement,
	minPriceIncrementAmount,
	displayFactor,
	tickRule,
	mainFraction,
	subFraction,
	priceDisplayFormat,
	unitOfMeasure,
	unitOfMeasureQty,
	tradingReferencePrice,
	settlPriceType,
	clearedVolume,
	openInterestQty,
	lowLimitPrice,
	highLimitPrice,
	userDefinedInstrument,
	tradingReferenceDate,
	noEvents,
 	noMDFeedTypes,
 	noInstAttrib,
 	noLotTypeRules,
 	noUnderlyings,
 	noRelatedInstruments,
 ))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionOption41::NoEvents, (), (
	eventType,
	eventTime,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionOption41::NoMDFeedTypes, (), (
	mDFeedType,
	marketDepth,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionOption41::NoInstAttrib, (), (
	instAttribValue,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionOption41::NoLotTypeRules, (), (
	lotType,
	minLotSize,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionOption41::NoUnderlyings, (), (
	underlyingSecurityID,
	underlyingSymbol,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionOption41::NoRelatedInstruments, (), (
	relatedSecurityID,
	relatedSymbol,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshTradeSummary42, (), (
	msg_size,
	message_header,
	transactTime,
	matchEventIndicator,
	block_padding,
	noMDEntries,
 	noOrderIDEntries,
 ))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshTradeSummary42::NoMDEntries, (), (
	mDEntryPx,
	mDEntrySize,
	securityID,
	rptSeq,
	numberOfOrders,
	aggressorSide,
	mDUpdateAction,
	mDTradeEntryID,
	padding,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshTradeSummary42::NoOrderIDEntries, (), (
	orderID,
	lastQty,
	padding,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshOrderBook43, (), (
	msg_size,
	message_header,
	transactTime,
	matchEventIndicator,
	block_padding,
	noMDEntries,
 ))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshOrderBook43::NoMDEntries, (), (
	orderID,
	mDOrderPriority,
	mDEntryPx,
	mDDisplayQty,
	securityID,
	mDUpdateAction,
	mDEntryType,
	padding,
))

BOOST_DESCRIBE_STRUCT(SnapshotFullRefreshOrderBook44, (), (
	msg_size,
	message_header,
	lastMsgSeqNumProcessed,
	totNumReports,
	securityID,
	noChunks,
	currentChunk,
	transactTime,
	noMDEntries,
 ))

BOOST_DESCRIBE_STRUCT(SnapshotFullRefreshOrderBook44::NoMDEntries, (), (
	orderID,
	mDOrderPriority,
	mDEntryPx,
	mDDisplayQty,
	mDEntryType,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshBook46, (), (
	msg_size,
	message_header,
	transactTime,
	matchEventIndicator,
	block_padding,
	noMDEntries,
 	noOrderIDEntries,
 ))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshBook46::NoMDEntries, (), (
	mDEntryPx,
	mDEntrySize,
	securityID,
	rptSeq,
	numberOfOrders,
	mDPriceLevel,
	mDUpdateAction,
	mDEntryType,
	padding,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshBook46::NoOrderIDEntries, (), (
	orderID,
	mDOrderPriority,
	mDDisplayQty,
	referenceID,
	orderUpdateAction,
	padding,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshOrderBook47, (), (
	msg_size,
	message_header,
	transactTime,
	matchEventIndicator,
	block_padding,
	noMDEntries,
 ))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshOrderBook47::NoMDEntries, (), (
	orderID,
	mDOrderPriority,
	mDEntryPx,
	mDDisplayQty,
	securityID,
	mDUpdateAction,
	mDEntryType,
	padding,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshTradeSummary48, (), (
	msg_size,
	message_header,
	transactTime,
	matchEventIndicator,
	block_padding,
	noMDEntries,
 	noOrderIDEntries,
 ))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshTradeSummary48::NoMDEntries, (), (
	mDEntryPx,
	mDEntrySize,
	securityID,
	rptSeq,
	numberOfOrders,
	aggressorSide,
	mDUpdateAction,
	mDTradeEntryID,
	padding,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshTradeSummary48::NoOrderIDEntries, (), (
	orderID,
	lastQty,
	padding,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshDailyStatistics49, (), (
	msg_size,
	message_header,
	transactTime,
	matchEventIndicator,
	block_padding,
	noMDEntries,
 ))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshDailyStatistics49::NoMDEntries, (), (
	mDEntryPx,
	mDEntrySize,
	securityID,
	rptSeq,
	tradingReferenceDate,
	settlPriceType,
	mDUpdateAction,
	mDEntryType,
	padding,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshLimitsBanding50, (), (
	msg_size,
	message_header,
	transactTime,
	matchEventIndicator,
	block_padding,
	noMDEntries,
 ))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshLimitsBanding50::NoMDEntries, (), (
	highLimitPrice,
	lowLimitPrice,
	maxPriceVariation,
	securityID,
	rptSeq,
))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshSessionStatistics51, (), (
	msg_size,
	message_header,
	transactTime,
	matchEventIndicator,
	block_padding,
	noMDEntries,
 ))

BOOST_DESCRIBE_STRUCT(MDIncrementalRefreshSessionStatistics51::NoMDEntries, (), (
	mDEntryPx,
	securityID,
	rptSeq,
	openCloseSettlFlag,
	mDUpdateAction,
	mDEntryType,
	mDEntrySize,
	padding,
))

BOOST_DESCRIBE_STRUCT(SnapshotFullRefresh52, (), (
	msg_size,
	message_header,
	lastMsgSeqNumProcessed,
	totNumReports,
	securityID,
	rptSeq,
	transactTime,
	lastUpdateTime,
	tradeDate,
	mDSecurityTradingStatus,
	highLimitPrice,
	lowLimitPrice,
	maxPriceVariation,
	noMDEntries,
 ))

BOOST_DESCRIBE_STRUCT(SnapshotFullRefresh52::NoMDEntries, (), (
	mDEntryPx,
	mDEntrySize,
	numberOfOrders,
	mDPriceLevel,
	tradingReferenceDate,
	openCloseSettlFlag,
	settlPriceType,
	mDEntryType,
))

BOOST_DESCRIBE_STRUCT(SnapshotFullRefreshOrderBook53, (), (
	msg_size,
	message_header,
	lastMsgSeqNumProcessed,
	totNumReports,
	securityID,
	noChunks,
	currentChunk,
	transactTime,
	noMDEntries,
 ))

BOOST_DESCRIBE_STRUCT(SnapshotFullRefreshOrderBook53::NoMDEntries, (), (
	orderID,
	mDOrderPriority,
	mDEntryPx,
	mDDisplayQty,
	mDEntryType,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionFuture54, (), (
	msg_size,
	message_header,
	matchEventIndicator,
	totNumReports,
	securityUpdateAction,
	lastUpdateTime,
	mDSecurityTradingStatus,
	applID,
	marketSegmentID,
	underlyingProduct,
	securityExchange,
	securityGroup,
	asset,
	symbol,
	securityID,
	securityType,
	cFICode,
	maturityMonthYear,
	currency,
	settlCurrency,
	matchAlgorithm,
	minTradeVol,
	maxTradeVol,
	minPriceIncrement,
	displayFactor,
	mainFraction,
	subFraction,
	priceDisplayFormat,
	unitOfMeasure,
	unitOfMeasureQty,
	tradingReferencePrice,
	settlPriceType,
	openInterestQty,
	clearedVolume,
	highLimitPrice,
	lowLimitPrice,
	maxPriceVariation,
	decayQuantity,
	decayStartDate,
	originalContractSize,
	contractMultiplier,
	contractMultiplierUnit,
	flowScheduleType,
	minPriceIncrementAmount,
	userDefinedInstrument,
	tradingReferenceDate,
	noEvents,
 	noMDFeedTypes,
 	noInstAttrib,
 	noLotTypeRules,
 ))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionFuture54::NoEvents, (), (
	eventType,
	eventTime,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionFuture54::NoMDFeedTypes, (), (
	mDFeedType,
	marketDepth,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionFuture54::NoInstAttrib, (), (
	instAttribValue,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionFuture54::NoLotTypeRules, (), (
	lotType,
	minLotSize,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionOption55, (), (
	msg_size,
	message_header,
	matchEventIndicator,
	totNumReports,
	securityUpdateAction,
	lastUpdateTime,
	mDSecurityTradingStatus,
	applID,
	marketSegmentID,
	underlyingProduct,
	securityExchange,
	securityGroup,
	asset,
	symbol,
	securityID,
	securityType,
	cFICode,
	putOrCall,
	maturityMonthYear,
	currency,
	strikePrice,
	strikeCurrency,
	settlCurrency,
	minCabPrice,
	matchAlgorithm,
	minTradeVol,
	maxTradeVol,
	minPriceIncrement,
	minPriceIncrementAmount,
	displayFactor,
	tickRule,
	mainFraction,
	subFraction,
	priceDisplayFormat,
	unitOfMeasure,
	unitOfMeasureQty,
	tradingReferencePrice,
	settlPriceType,
	clearedVolume,
	openInterestQty,
	lowLimitPrice,
	highLimitPrice,
	userDefinedInstrument,
	tradingReferenceDate,
	noEvents,
 	noMDFeedTypes,
 	noInstAttrib,
 	noLotTypeRules,
 	noUnderlyings,
 	noRelatedInstruments,
 ))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionOption55::NoEvents, (), (
	eventType,
	eventTime,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionOption55::NoMDFeedTypes, (), (
	mDFeedType,
	marketDepth,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionOption55::NoInstAttrib, (), (
	instAttribValue,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionOption55::NoLotTypeRules, (), (
	lotType,
	minLotSize,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionOption55::NoUnderlyings, (), (
	underlyingSecurityID,
	underlyingSymbol,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionOption55::NoRelatedInstruments, (), (
	relatedSecurityID,
	relatedSymbol,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionSpread56, (), (
	msg_size,
	message_header,
	matchEventIndicator,
	totNumReports,
	securityUpdateAction,
	lastUpdateTime,
	mDSecurityTradingStatus,
	applID,
	marketSegmentID,
	underlyingProduct,
	securityExchange,
	securityGroup,
	asset,
	symbol,
	securityID,
	securityType,
	cFICode,
	maturityMonthYear,
	currency,
	securitySubType,
	userDefinedInstrument,
	matchAlgorithm,
	minTradeVol,
	maxTradeVol,
	minPriceIncrement,
	displayFactor,
	priceDisplayFormat,
	priceRatio,
	tickRule,
	unitOfMeasure,
	tradingReferencePrice,
	settlPriceType,
	openInterestQty,
	clearedVolume,
	highLimitPrice,
	lowLimitPrice,
	maxPriceVariation,
	mainFraction,
	subFraction,
	tradingReferenceDate,
	noEvents,
 	noMDFeedTypes,
 	noInstAttrib,
 	noLotTypeRules,
 	noLegs,
 ))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionSpread56::NoEvents, (), (
	eventType,
	eventTime,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionSpread56::NoMDFeedTypes, (), (
	mDFeedType,
	marketDepth,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionSpread56::NoInstAttrib, (), (
	instAttribValue,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionSpread56::NoLotTypeRules, (), (
	lotType,
	minLotSize,
))

BOOST_DESCRIBE_STRUCT(MDInstrumentDefinitionSpread56::NoLegs, (), (
	legSecurityID,
	legSide,
	legRatioQty,
	legPrice,
	legOptionDelta,
))

BOOST_DESCRIBE_STRUCT(extended_message_header, (),
                      (msg_size,
                       blockLength,
                       templateId))

} // namespace cme::mdp3::v9
